### ISSUE TITLE
SEO and Tracking Implementation

### ISSUE THREAD

**Issue by D-T-Design** [D-T-Design/dtdesign-netlify-next#1]
## Make sure site is using SEO and Tracking best practices.

Check for the following:

- [x] Google Analytics Tag
- [x] Facebook Pixel
- [x] Page Titles & Meta Descriptions
- [x] OpenGraph Head Tags
- [x] Sitemap and Robots working correctly

**Comment by D-T-Design** [comment]
Added site-wide Google tracking in this commit: https://github.com/D-T-Design/dtdesign-netlify-next/commit/0b235363ae03b0815f48435a727de213839d6134

**Comment by D-T-Design** [comment]
Page titles and meta descriptions are customized for each page via next/head:
https://github.com/D-T-Design/dtdesign-netlify-next/commit/739f2e6e834c5738136a52609512b02a2c2161da
`<Head>
			<title>{props.title}</title>
			<meta name="description" content={props.description} />
			<meta property="og:title" content={props.title} key="title" />
			<meta property="og:description" content={props.description} />
		</Head>`

**Comment by D-T-Design** [comment]
Added in Facebook Pixel tracking and SDK access.
https://github.com/D-T-Design/dtdesign-netlify-next/commit/0d26bf6dc1fa994e8fa45b22683f4ca2987c6989

**Comment by D-T-Design** [comment]
Added in sitemap and robots.txt

https://github.com/D-T-Design/dtdesign-netlify-next/commit/d112587cea8f9fe6b30ed6cef2db75a31d63ee05
